2018-08-09 23:42:43,157 - G:/Tool/Python/work/workApp/testdemo/logutils.py[line:38] - ERROR: error
